# Generated by Django 5.0.1 on 2024-01-29 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datamodel',
            old_name='actor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='datamodel',
            old_name='director',
            new_name='category',
        ),
    ]
